local colors = require("palettes").get_palette()

require("catppuccin").setup({
    flavour = "mocha", -- latte, frappe, macchiato, mocha
    background = { -- :h background
        light = "latte",
        dark = "mocha",
    },
    compile_path = vim.fn.stdpath("cache") .. "/catppuccin",
    transparent_background = true,
    term_colors = false,
    dim_inactive = {
        enabled = false,
        shade = "dark",
        percentage = 0.15,
    },
    styles = {
        comments = { "italic" },
        conditionals = { "italic" },
        loops = {},
        functions = {},
        keywords = {},
        strings = {},
        variables = {},
        numbers = {},
        booleans = {},
        properties = {},
        types = {},
        operators = {},
    },
    color_overrides = {
      all = colors,
    },
    integrations = {
        cmp = true,
        dap = true,
        dap_ui = true,
        dashboard = true,
        indent_blankline = { enabled = true, scope_color = "teal" },
        gitsigns = true,
        mason = true,
        native_lsp = { enabled = true },
        notify = true,
        nvimtree = true,
        telescope = true,
        treesitter = true,
        which_key = true,
    },
    custom_highlights = function(C)
      local transparent_background = true
			return {
        Normal = { fg = colors.text, bg = transparent_background and C.none or colors.base },
        NormalNC = { fg = colors.subtext1, bg = transparent_background and C.none or colors.base },
        NormalFloat = { fg = colors.text, bg = colors.surface0 },
        FloatBorder = { fg = colors.pink, bg = colors.surface0 },
        FloatTitle = { fg = colors.teal, bg = colors.surface0, style = { "bold" } },
        Pmenu = { fg = colors.text, bg = colors.surface0 },
        PmenuSel = { fg = colors.base, bg = colors.teal, style = { "bold" } },
        PmenuSbar = { bg = colors.surface1 },
        PmenuThumb = { bg = colors.pink },
        CursorLine = { bg = colors.surface0 },
        CursorLineNr = { fg = colors.teal, style = { "bold" } },
        LineNr = { fg = colors.overlay0 },
        Visual = { bg = colors.surface2 },
        Search = { fg = colors.base, bg = colors.pink },
        IncSearch = { fg = colors.base, bg = colors.teal },
        MatchParen = { fg = colors.teal, bg = colors.surface1, style = { "bold" } },
        DiagnosticVirtualTextError = { fg = colors.red, bg = colors.mantle },
        DiagnosticVirtualTextWarn = { fg = colors.yellow, bg = colors.mantle },
        DiagnosticVirtualTextInfo = { fg = colors.sky, bg = colors.mantle },
        DiagnosticVirtualTextHint = { fg = colors.teal, bg = colors.mantle },
        TelescopeBorder = { fg = colors.surface2, bg = colors.mantle },
        TelescopeNormal = { fg = colors.text, bg = colors.mantle },
        TelescopePromptBorder = { fg = colors.pink, bg = colors.surface0 },
        TelescopePromptNormal = { fg = colors.text, bg = colors.surface0 },
        TelescopePromptPrefix = { fg = colors.teal, bg = colors.surface0 },
        TelescopeSelection = { fg = colors.text, bg = colors.surface1, style = { "bold" } },
        WhichKeyNormal = { bg = colors.mantle },
        WinSeparator = {
			    fg = colors.surface1,
			    bg = transparent_background and C.none or C.base,
        },
        NvimTreeNormal = { fg = colors.subtext1, bg = transparent_background and C.none or colors.base },
        NvimTreeRootFolder = { fg = colors.teal, style = { "bold" } },
        NvimTreeFolderName = { fg = colors.sky },
        NvimTreeOpenedFolderName = { fg = colors.teal, style = { "bold" } },
        NvimTreeFolderIcon = { fg = colors.sky },
        NvimTreeIndentMarker = { fg = colors.overlay0 },
        NvimTreeGitDirty = { fg = colors.pink },
        NvimTreeGitNew = { fg = colors.green },
        NvimTreeGitDeleted = { fg = colors.red },
        DashboardHeader = { fg = colors.teal },
        DashboardCenter = { fg = colors.lavender },
        DashboardShortcut = { fg = colors.pink },
        DashboardFooter = { fg = colors.overlay2 },
				CmpItemKindSnippet = { fg = colors.base, bg = colors.mauve },
				CmpItemKindKeyword = { fg = colors.base, bg = colors.pink },
				CmpItemKindText = { fg = colors.base, bg = colors.teal },
				CmpItemKindMethod = { fg = colors.base, bg = colors.blue },
				CmpItemKindConstructor = { fg = colors.base, bg = colors.blue },
				CmpItemKindFunction = { fg = colors.base, bg = colors.blue },
				CmpItemKindFolder = { fg = colors.base, bg = colors.blue },
				CmpItemKindModule = { fg = colors.base, bg = colors.blue },
				CmpItemKindConstant = { fg = colors.base, bg = colors.peach },
				CmpItemKindField = { fg = colors.base, bg = colors.green },
				CmpItemKindProperty = { fg = colors.base, bg = colors.green },
				CmpItemKindEnum = { fg = colors.base, bg = colors.green },
				CmpItemKindUnit = { fg = colors.base, bg = colors.green },
				CmpItemKindClass = { fg = colors.base, bg = colors.yellow },
				CmpItemKindVariable = { fg = colors.base, bg = colors.flamingo },
				CmpItemKindFile = { fg = colors.base, bg = colors.blue }, CmpItemKindInterface = { fg = colors.base, bg = colors.yellow },
				CmpItemKindColor = { fg = colors.base, bg = colors.pink },
				CmpItemKindReference = { fg = colors.base, bg = colors.pink },
				CmpItemKindEnumMember = { fg = colors.base, bg = colors.pink },
				CmpItemKindStruct = { fg = colors.base, bg = colors.blue },
				CmpItemKindValue = { fg = colors.base, bg = colors.peach },
				CmpItemKindEvent = { fg = colors.base, bg = colors.blue },
				CmpItemKindOperator = { fg = colors.base, bg = colors.blue },
				CmpItemKindTypeParameter = { fg = colors.base, bg = colors.blue },
				CmpItemKindCopilot = { fg = colors.base, bg = colors.teal },
		  	NvimTreeWinSeparator = {
			    fg = colors.surface1,
			    bg = transparent_background and C.none or C.base,
		    },
    }
	  end,   
})

vim.cmd('colorscheme catppuccin')
--FOR ZENMODE
vim.cmd("highlight ZenBg guibg=" .. colors.mantle)
